configName: crypto_v4_apii_test_pic32cz_ca90
folderName: crypto_v4_api_mcc
format_version: v1.0
frameworkPath: C:\Microchip\harmony\h3_v400S
processor: PIC32CZ8110CA90208
projectName: crypto_v4_api_mcc
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  MERGE_STRATEGY: USER_ALL
  DFPPath: PIC32CZ-CA90_DFP\1.3.152
