package:
  format-version: "1.0.0"
  name: "crypto"
  type: "api"
  status: "production"
  required: false
  version: "dev"

  dependencies:
    - name: "core"
      type: "package"
      version: "v3.13.1"
    - name: "wolfssl"
      type: "package"
      version: "v5.6.6"
    - name: "zlib"
      type: "package"
      version: "v1.2.11"
